// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
module myproject_dense_resource_rf_gt_nin_rem0_ap_ufixed_ap_fixed_config14_mult_s_outidx_72_RO6jw (
    address0, ce0, q0, 
    reset, clk);

parameter DataWidth = 1;
parameter AddressWidth = 7;
parameter AddressRange = 108;
 
input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0;

input reset;
input clk;

 
reg [DataWidth-1:0] rom0[0:AddressRange-1];


initial begin
     
    $readmemh("./myproject_dense_resource_rf_gt_nin_rem0_ap_ufixed_ap_fixed_config14_mult_s_outidx_72_RO6jw.dat", rom0);
end

  
always @(posedge clk) 
begin 
    if (ce0) 
    begin
        q0 <= rom0[address0];
    end
end


endmodule

