# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/master.xdc

# Block Designs: bd/design_4/design_4.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4 || ORIG_REF_NAME==design_4} -quiet] -quiet

# IP: bd/design_4/ip/design_4_clk_wiz_0_0/design_4_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_clk_wiz_0_0 || ORIG_REF_NAME==design_4_clk_wiz_0_0} -quiet] -quiet

# XDC: /home/petertso/Documents/753-FPGA/spi-controller-cmod-a7-2024.2/spi-controller-cmod-a7-2024.2.gen/sources_1/bd/design_4/design_4_ooc.xdc
