Backend: Vitis
ClockPeriod: 30
ClockUncertainty: 27%
HLSConfig:
  LayerName:
    conv1:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: auto
        bias: fixed<6,2,TRN,WRAP,0>
        result: auto
        weight: fixed<6,2,TRN,WRAP,0>
      ReuseFactor: 64
      Trace: false
    conv1_linear:
      Precision:
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 64
      TableSize: 1024
      Trace: false
    flatten_2:
      Precision:
        result: auto
      Trace: false
    input_1:
      Precision:
        result: ap_uint<8>
      Trace: false
    output_1:
      Precision:
        accum: auto
        bias: fixed<6,2,TRN,WRAP,0>
        result: ap_fixed<16,6>
        weight: fixed<6,2,TRN,WRAP,0>
      ReuseFactor: 64
      Trace: false
    output_1_linear:
      Precision:
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 64
      TableSize: 1024
      Trace: false
    q_activation_6:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT,0>
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 64
      TableSize: 1024
      Trace: false
    q_activation_7:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT,0>
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 64
      TableSize: 1024
      Trace: false
    q_activation_8:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT,0>
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 64
      TableSize: 1024
      Trace: false
    q_conv2d_11:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: auto
        bias: fixed<6,2,TRN,WRAP,0>
        result: auto
        weight: fixed<6,2,TRN,WRAP,0>
      ReuseFactor: 64
      Trace: false
    q_conv2d_11_linear:
      Precision:
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 64
      TableSize: 1024
      Trace: false
    q_conv2d_9:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: auto
        bias: fixed<6,2,TRN,WRAP,0>
        result: auto
        weight: fixed<6,2,TRN,WRAP,0>
      ReuseFactor: 64
      Trace: false
    q_conv2d_9_linear:
      Precision:
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 64
      TableSize: 1024
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision:
      default: ap_fixed<4,0>
    ReuseFactor: 64
    Strategy: Resource
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model 'tmp/tmp_prj/keras_model.keras'
OutputDir: tmp/tmp_prj
OutputPredictions: null
Part: xc7a35tcpg236-1
ProjectName: myproject
Stamp: 7ead5dc8
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
