-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_shift_line_buffer_array_ap_uint_8_1u_config2_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    in_elem_0_0_0_0_0_val : IN STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_i : IN STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9 : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_i : IN STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_13_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_13_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_13_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_14 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_14_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_8_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_8_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_8_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_9 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_9_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_3_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_3_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_3_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_4 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_4_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_i : IN STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_i : IN STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_12_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_12_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_12_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_7_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_7_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_7_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_2_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_2_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_2_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_i : IN STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_i : IN STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_11_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_11_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_11_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_6_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_6_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_6_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_1_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_1_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_1_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_i : IN STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_i : IN STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_10_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_10_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_10_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_5_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_5_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_5_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of myproject_shift_line_buffer_array_ap_uint_8_1u_config2_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_3_ce0 : STD_LOGIC;
    signal void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_3_we0 : STD_LOGIC;
    signal void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_3_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_2_ce0 : STD_LOGIC;
    signal void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_2_we0 : STD_LOGIC;
    signal void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1_ce0 : STD_LOGIC;
    signal void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1_we0 : STD_LOGIC;
    signal void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_ce0 : STD_LOGIC;
    signal void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_we0 : STD_LOGIC;
    signal void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_1_i_reg_357 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_shift_line_buffer_array_ap_uint_8_1u_config2_s_void_conv_2d_buffer_latency_clbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_3_U : component myproject_shift_line_buffer_array_ap_uint_8_1u_config2_s_void_conv_2d_buffer_latency_clbkb
    generic map (
        DataWidth => 8,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_3F,
        ce0 => void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_3_ce0,
        we0 => void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_3_we0,
        d0 => in_elem_0_0_0_0_0_val,
        q0 => void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_3_q0);

    void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_2_U : component myproject_shift_line_buffer_array_ap_uint_8_1u_config2_s_void_conv_2d_buffer_latency_clbkb
    generic map (
        DataWidth => 8,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_3F,
        ce0 => void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_2_ce0,
        we0 => void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_2_we0,
        d0 => void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_3_q0,
        q0 => void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_2_q0);

    void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1_U : component myproject_shift_line_buffer_array_ap_uint_8_1u_config2_s_void_conv_2d_buffer_latency_clbkb
    generic map (
        DataWidth => 8,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_3F,
        ce0 => void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1_ce0,
        we0 => void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1_we0,
        d0 => p_1_i_reg_357,
        q0 => void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1_q0);

    void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_U : component myproject_shift_line_buffer_array_ap_uint_8_1u_config2_s_void_conv_2d_buffer_latency_clbkb
    generic map (
        DataWidth => 8,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_3F,
        ce0 => void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_ce0,
        we0 => void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_we0,
        d0 => void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1_q0,
        q0 => void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                p_1_i_reg_357 <= void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_2_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_10_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_10_i, void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_2_q0, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_10_o <= void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_2_q0;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_10_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_10_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_10_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_10_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_10_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_11_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_11_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_10_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_11_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_10_i;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_11_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_11_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_11_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_11_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_11_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_12_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_12_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_11_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_12_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_11_i;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_12_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_12_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_12_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_12_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_12_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_13_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_13_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_12_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_13_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_12_i;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_13_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_13_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_13_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_13_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_13_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_14 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_13_i;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_14_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_14_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_14_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_1_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_1_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_1_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_i;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_1_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_1_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_1_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_1_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_2_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_2_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_1_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_2_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_1_i;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_2_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_2_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_2_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_2_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_2_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_3_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_3_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_2_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_3_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_2_i;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_3_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_3_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_3_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_3_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_3_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_4 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_3_i;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_4_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_4_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_5_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_5_i, void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_3_q0, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_5_o <= void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_3_q0;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_5_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_5_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_5_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_5_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_5_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_6_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_6_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_5_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_6_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_5_i;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_6_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_6_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_6_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_6_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_6_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_7_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_7_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_6_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_7_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_6_i;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_7_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_7_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_7_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_7_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_7_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_8_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_8_i, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_7_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_8_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_7_i;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_8_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_8_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_8_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_8_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_8_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_9 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_8_i;

    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_9_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_9_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_9_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, in_elem_0_0_0_0_0_val, p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_o <= in_elem_0_0_0_0_0_val;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_o <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI7ap_uintILi8EELj1EEENS1_I8ap_fixed_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_i, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_i;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_i, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_i;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_i, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_i;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_i;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_i, void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_q0, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o <= void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_q0;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_i, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_i;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_i, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_i;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_i, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_i;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_i;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_i, void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1_q0, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o <= void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1_q0;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1_ce0 <= ap_const_logic_1;
        else 
            void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1_we0 <= ap_const_logic_1;
        else 
            void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_2_ce0 <= ap_const_logic_1;
        else 
            void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_2_we0 <= ap_const_logic_1;
        else 
            void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_3_ce0 <= ap_const_logic_1;
        else 
            void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_3_we0 <= ap_const_logic_1;
        else 
            void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_ce0 <= ap_const_logic_1;
        else 
            void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_we0 <= ap_const_logic_1;
        else 
            void_conv_2d_buffer_latency_cl_stream_stream_weight_t_bias_t_line_buffer_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
