Backend: Vitis
ClockPeriod: 100
ClockUncertainty: 27%
HLSConfig:
  LayerName:
    conv1:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: auto
        bias: fixed<6,2,TRN,WRAP,0>
        result: auto
        weight: fixed<6,2,TRN,WRAP,0>
      ReuseFactor: 64
      Trace: false
    conv1_linear:
      Precision:
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 64
      TableSize: 1024
      Trace: false
    flatten_6:
      Precision:
        result: auto
      Trace: false
    input_1:
      Precision:
        result: ap_uint<8>
      Trace: false
    output_1:
      Precision:
        accum: auto
        bias: fixed<6,2,TRN,WRAP,0>
        result: auto
        weight: fixed<6,2,TRN,WRAP,0>
      ReuseFactor: 64
      Trace: false
    output_1_linear:
      Precision:
        result: ap_fixed<16,6>
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 64
      TableSize: 1024
      Trace: false
    q_activation_18:
      Precision:
        result: fixed<8,1,RND_CONV,SAT,0>
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 64
      TableSize: 1024
      Trace: false
    q_activation_19:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT,0>
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 64
      TableSize: 1024
      Trace: false
    q_activation_20:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT,0>
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 64
      TableSize: 1024
      Trace: false
    q_activation_21:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT,0>
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 64
      TableSize: 1024
      Trace: false
    q_activation_22:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT,0>
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 64
      TableSize: 1024
      Trace: false
    q_conv2d_24:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: auto
        bias: fixed<6,2,TRN,WRAP,0>
        result: auto
        weight: fixed<6,2,TRN,WRAP,0>
      ReuseFactor: 64
      Trace: false
    q_conv2d_24_linear:
      Precision:
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 64
      TableSize: 1024
      Trace: false
    q_conv2d_26:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: auto
        bias: fixed<6,2,TRN,WRAP,0>
        result: auto
        weight: fixed<6,2,TRN,WRAP,0>
      ReuseFactor: 64
      Trace: false
    q_conv2d_26_linear:
      Precision:
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 64
      TableSize: 1024
      Trace: false
    q_conv2d_27:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: auto
        bias: fixed<6,2,TRN,WRAP,0>
        result: auto
        weight: fixed<6,2,TRN,WRAP,0>
      ReuseFactor: 64
      Trace: false
    q_conv2d_27_linear:
      Precision:
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 64
      TableSize: 1024
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision:
      default: ap_fixed<4,0>
    ReuseFactor: 64
    Strategy: Resource
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model './tmp/tmp_prj/keras_model.keras'
OutputDir: ./tmp/tmp_prj
OutputPredictions: null
Part: xc7a35tcpg236-1
ProjectName: myproject
Stamp: e4459c13
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
